import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        pri: "#36454F",
        beig: "#7d98a1",
        gr: "#008080",
        brown: "#6f432a",
        terracotta: "#E3735E",
        sienna: "#a0522d",
        taupe: "#483C32",
        burntOrange: "#cc5500",
        sage: "#B2AC88",
        copper: "#b87333",
        mocha: "#bea493",
        midnightBlue: "#191970",
        nightBlue: "#2d545e",
        sandTanShadow: "#8076a3",
        mountainBlue: "#101357",
        charcoal: "#36454F",
        forestGreen: " #228B22",
        burgundy: "#800020",
        jetBlack: "#343434",
        chocoBrown: "#411900",
        onyx: "#353839",
        primary: "var(--primary)",
        "primary-2": "var(--primary-2)",
        secondary: "var(--secondary)",
        "secondary-2": "var(--secondary-2)",
        hover: "var(--hover)",
        "hover-1": "var(--hover-1)",
        "hover-2": "var(--hover-2)",
        "accents-0": "var(--accents-0)",
        "accents-1": "var(--accents-1)",
        "accents-2": "var(--accents-2)",
        "accents-3": "var(--accents-3)",
        "accents-4": "var(--accents-4)",
        "accents-5": "var(--accents-5)",
        "accents-6": "var(--accents-6)",
        "accents-7": "var(--accents-7)",
        "accents-8": "var(--accents-8)",
        "accents-9": "var(--accents-9)",
        violet: "var(--violet)",
        "violet-light": "var(--violet-light)",
        pink: "var(--pink)",
        cyan: "var(--cyan)",
        blue: "var(--blue)",
        green: "var(--green)",
        red: "var(--red)",
      },
    },
  },
  plugins: [],
};
export default config;
